added try good first issue
ayan-biswas0412/gssoc2021-HotelOnTouch pull request #129
Opened 2021-03-17 18:05 UTC by shreyanshi16

Fixes #52

#### Changes done

- [Added try good first issue section ]

Screenshots of the changes (If any) -
![image](https://user-images.githubusercontent.com/53462278/111515759-2d8dea80-8779-11eb-918d-ddcf776c4b0b.png)

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [ ✅️] Worked on forked repo and starred the main repo
- [ ✅️] Checked to see if a similar PR has already been opened 🤔️
- [ ✅️] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

2021-03-17 18:16 UTC, ayan-biswas0412 requested changes
remove yarn lock and change the violet colour change it to blue and point the button to level1 issues as we have no good first issues

2021-03-17 18:53 UTC, shreyanshi16 commented
@ayan-biswas0412 I have made all the changes. Please tell me if you need any other changes.

2021-03-18 08:34 UTC, ayan-biswas0412 submitted a review, later dismissed
good work

2021-03-18 09:47 UTC, shreyanshi16 commented
Thank you!

2021-03-21 22:05 UTC, ayan-biswas0412 requested changes
this PR was approved but you have messed up your work

2021-03-22 09:24 UTC, shreyanshi16 commented
Yeah, I am so sorry. Actually, I was working on the contact-us page and mistakenly I made a commit on this branch. I also tried to uncommit the last commit but that didn't work out. Can you please guide me on how to fix this code again.

2021-03-22 11:01 UTC, ayan-biswas0412 commented
> Yeah, I am so sorry. Actually, I was working on the contact-us page and mistakenly I made a commit on this branch. I also tried to uncommit the last commit but that didn't work out. Can you please guide me on how to fix this code again.

see this https://www.freecodecamp.org/news/how-to-undo-changes-in-git-e1da7930afdb/

2021-03-22 14:45 UTC, shreyanshi16 commented
Code fixed! Thank you for your help :)

2021-03-22 16:03 UTC, ayan-biswas0412 requested changes
most of the ci checks are failed

2021-03-23 12:10 UTC, ayan-biswas0412 requested changes
ci checks are still failing

2021-03-23 17:00 UTC, shreyanshi16 commented
Yes i am trying to debug them.

2021-03-28 17:26 UTC, aniketsingh98571 commented
> Yes i am trying to debug them.

@shreyanshi16 I think there is a problem with your `upstream`....

2021-03-29 07:17 UTC, shreyanshi16 commented
Hey, @aniketsingh98571 I have tried all the possible ways to resolve it but failed. If you have any idea of how to resolve it then will you please guide me?

2021-03-29 07:32 UTC, aniketsingh98571 commented
@shreyanshi16 
1. You must be missing some "}" or something in your package.json file just check it out or compare it with the old version of your file it helped me out many times
2.  forget to give a comma "," in my JSON file.

2021-03-29 07:33 UTC, aniketsingh98571 commented
@shreyanshi16  Please refer [this](https://dev.to/redslug/7-solutions-to-ejsonparse-or-unexpected-token-npm-install-error-20nh)

2021-03-30 08:15 UTC, shreyanshi16 commented
@aniketsingh98571 Thank you for your effort. I tried all solutions you suggested but I am not being able to resolve them.

2021-03-30 09:04 UTC, aniketsingh98571 requested changes
Have you changed package.json ...

2021-03-30 09:04 UTC, aniketsingh98571 commented on hotelontouch/package.json
> +    "name": "hotelontouch",
Where is opening bracket `{` before `"name":"hotelontouch"`

2021-04-06 22:07 UTC, ayan-biswas0412 requested changes
all the ci s are failing

2021-04-27 19:37 UTC, closed without merging