adding react-router-dom and react-bootstrap.
ayan-biswas0412/gssoc2021-HotelOnTouch pull request #27
Opened 2021-02-20 11:34 UTC by Doringl

2021-02-20 12:01 UTC, ayan-biswas0412 requested changes
please change the file I have commented

2021-02-20 12:01 UTC, ayan-biswas0412 commented on hotel-admin-frontend/src/pages/HomePage.jsx
> +import Wrapper from '../components/Wrapper';
import Wrapper from '../components'; // make a indx.js file in the ```components``` and export the components from there.

2021-02-20 12:01 UTC, ayan-biswas0412 commented on hotel-admin-frontend/src/App.js
> +import { Switch, Route } from 'react-router-dom';
import HomePage from './pages' // also make index.js inside pages and export all page from there

2021-02-20 14:50 UTC, ayan-biswas0412 reviewed
your PR description is empty please follow the PR template

2021-02-20 15:13 UTC, Doringl commented
I write a description.

2021-02-20 15:34 UTC, ayan-biswas0412 commented
> I write a description.

you haven't completed the onboarding process please do that, See the Contributing Section in Readme

2021-02-20 16:11 UTC, Doringl commented
I cant write info about myself now im busy a bit, you merge if you want.

2021-02-21 14:12 UTC, ayan-biswas0412 approved these changes
nice

2021-02-21 14:15 UTC, ayan-biswas0412 requested changes
all your files are .jsx but it should be .js

2021-02-21 14:25 UTC, Doringl commented
because they are return react component but I will fix it.

2021-02-21 17:41 UTC, ayan-biswas0412 approved these changes

2021-02-21 17:45 UTC, merged