Footer
ayan-biswas0412/gssoc2021-HotelOnTouch pull request #46
Opened 2021-02-24 16:24 UTC by batman005

added a wave Footer with material ui icons 
Screenshots of the changes (If any) -
![wave footer](https://user-images.githubusercontent.com/51878340/109031491-cb4a4880-76ea-11eb-9899-b90c712e3072.JPG)

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [ ] Worked on forked repo and starred the main repo
- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

2021-02-24 16:28 UTC, ayan-biswas0412 requested changes

2021-02-24 16:28 UTC, ayan-biswas0412 commented on hotelontouch/src/App.js
> +import Footer from './components/Footer.js';
export the component in ```components/index.js``` as ```export { dafault as Footer } from './Footer';``` and then import here as ```import Footer from './components';```

2021-02-24 16:29 UTC, ayan-biswas0412 requested changes
And also see your CI checks are failing fix them

2021-02-24 16:39 UTC, batman005 commented
okay I will try to fix those issue ,btw thank you for reviewing it

2021-02-24 17:25 UTC, aniketsingh98571 commented
@batman005 , remove all the whitespaces which are there in your files, if you have any link with `href="#"` replace it with `href="/"`

2021-02-24 18:01 UTC, ayan-biswas0412 commented
> @batman005 , remove all the whitespaces which are there in your files, if you have any link with `href="#"` replace it with `href="/"`

Good @aniketsingh98571 to review works in this repository 🥰

2021-02-25 04:48 UTC, batman005 commented
@aniketsingh98571  thankyouu for the tip

2021-02-25 05:49 UTC, aniketsingh98571 commented
@batman005  please refer to #45 for CI checks

2021-02-25 06:23 UTC, batman005 commented
@ayan-biswas0412    I have made all the changes now the footer will work in all the devices  ipad,mobile,laptop,desktop at 100% zoom ,please have a look

2021-02-25 17:34 UTC, ayan-biswas0412 requested changes
your footer height is so large please reduce it

2021-02-25 17:35 UTC, ayan-biswas0412 commented
> @ayan-biswas0412 I have made all the changes now the footer will work in all the devices ipad,mobile,laptop,desktop at 100% zoom ,please have a look.
> ( I think we can also add payment types to the website and link into the footer )

yeah it is a good idea and please open an issue regarding this with proper implementation

2021-02-26 12:48 UTC, batman005 commented
> your footer height is so large please reduce it

reduced the size of footer ,have look..

2021-02-26 12:52 UTC, batman005 commented
> > @ayan-biswas0412 I have made all the changes now the footer will work in all the devices ipad,mobile,laptop,desktop at 100% zoom ,please have a look.
> > ( I think we can also add payment types to the website and link into the footer )
> 
> yeah it is a good idea and please open an issue regarding this with proper implementation

okay great, but it will take time because I am in the middle of my semester exams...

2021-02-26 15:32 UTC, ayan-biswas0412 requested changes
again the white space issue is not resolved, please resolve that otherwise I can't merge this

2021-02-27 04:02 UTC, batman005 commented
mobile view (iphone X) 100% zoom
![iphone view](https://user-images.githubusercontent.com/51878340/109374573-6b1af880-78dc-11eb-993f-988708c6402e.JPG)
ipad view 100% zoom
![ipad view](https://user-images.githubusercontent.com/51878340/109374593-838b1300-78dc-11eb-8c3c-e1891cf68174.JPG)
ipad pro view 100% zoom
![ipad pro view](https://user-images.githubusercontent.com/51878340/109374607-93a2f280-78dc-11eb-9796-05e763685d3a.JPG)
desktop view at full scroll
![desktop view](https://user-images.githubusercontent.com/51878340/109374619-a87f8600-78dc-11eb-974f-b520ab77a93d.JPG)

@ayan-biswas0412  sir I used an  SVG so it is a static  wave because when we are using  react-wavify with style-component we aren't able to stick the footer at the bottom of  web app with the animation (example devices :- desktop(24 inch monitor), ipad and i padpro )
I think we should use an alternative for animation like CSS...

2021-02-27 08:16 UTC, ayan-biswas0412 commented
> mobile view (iphone X) 100% zoom
> ![iphone view](https://user-images.githubusercontent.com/51878340/109374573-6b1af880-78dc-11eb-993f-988708c6402e.JPG)
> ipad view 100% zoom
> ![ipad view](https://user-images.githubusercontent.com/51878340/109374593-838b1300-78dc-11eb-8c3c-e1891cf68174.JPG)
> ipad pro view 100% zoom
> ![ipad pro view](https://user-images.githubusercontent.com/51878340/109374607-93a2f280-78dc-11eb-9796-05e763685d3a.JPG)
> desktop view at full scroll
> ![desktop view](https://user-images.githubusercontent.com/51878340/109374619-a87f8600-78dc-11eb-974f-b520ab77a93d.JPG)
> 
> @ayan-biswas0412 sir I used an SVG so it is a static wave because when we are using react-wavify with style-component we aren't able to stick the footer at the bottom of web app with the animation (example devices :- desktop(24 inch monitor), ipad and i padpro )
> I think we should use an alternative for animation like CSS...

if you want to use another alternative you may use that

2021-02-28 14:07 UTC, batman005 commented
![wave in desktop](https://user-images.githubusercontent.com/51878340/109421140-1f5f7080-79fc-11eb-8545-9a3c3e6b4949.JPG)
wave animation in desktop
![iphone static](https://user-images.githubusercontent.com/51878340/109421154-2d14f600-79fc-11eb-9e6b-0cbda64d15ae.JPG)
normal static footer in mobile view

@ayan-biswas0412  sir can we go for this type of footer option

2021-02-28 14:35 UTC, ayan-biswas0412 commented
> ![wave in desktop](https://user-images.githubusercontent.com/51878340/109421140-1f5f7080-79fc-11eb-8545-9a3c3e6b4949.JPG)
> wave animation in desktop
> ![iphone static](https://user-images.githubusercontent.com/51878340/109421154-2d14f600-79fc-11eb-9e6b-0cbda64d15ae.JPG)
> normal static footer in mobile view
> 
> @ayan-biswas0412 sir can we go for this type of footer option like static Footer in mobile view and wave animation footer in desktop ipad etc. i means in landscape mode.

no dear it is highly discouraged to change style according to the device

2021-02-28 14:47 UTC, batman005 commented
> > ![wave in desktop](https://user-images.githubusercontent.com/51878340/109421140-1f5f7080-79fc-11eb-8545-9a3c3e6b4949.JPG)
> > wave animation in desktop
> > ![iphone static](https://user-images.githubusercontent.com/51878340/109421154-2d14f600-79fc-11eb-9e6b-0cbda64d15ae.JPG)
> > normal static footer in mobile view
> > @ayan-biswas0412 sir can we go for this type of footer option like static Footer in mobile view and wave animation footer in desktop ipad etc. i means in landscape mode.
> 
> no dear it is highly discouraged to change style according to the device

@ayan-biswas0412  okay sir,I have made some changes please have a look into it.....

2021-02-28 14:52 UTC, batman005 commented
@ayan-biswas0412  okay sir, I  have made some changes  on the footer please  look into it..
(sir i have a doubt also do we get mentors in  gssoc 2021? )

2021-02-28 14:53 UTC, ayan-biswas0412 commented
> @ayan-biswas0412 okay sir, I have made some changes on the footer please look into it..
> (sir i have a doubt also do we get mentors in gssoc 2021? )

mobile view is still very scattered and not well resized

2021-02-28 14:54 UTC, ayan-biswas0412 commented
> @ayan-biswas0412 okay sir, I have made some changes on the footer please look into it..
> (sir i have a doubt also do we get mentors in gssoc 2021? )

regarding your doubt I think I am not the right person to tell that you can clarify your doubt from the GSSoc officials only

2021-03-20 15:22 UTC, closed without merging