Readme.md of hotelontouch #44
ayan-biswas0412/gssoc2021-HotelOnTouch pull request #60
Opened 2021-03-02 16:36 UTC by aniketsingh98571

Fixes #
#44 

Added Readme.md

- [ ]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

2021-03-02 17:35 UTC, ayan-biswas0412 requested changes
1. You have given only file structures not how to setup and run the app I said preciously to give links to that also from this repository's wiki please include that
2. remove your modified package-lock.json

2021-03-03 06:32 UTC, aniketsingh98571 commented
@ayan-biswas0412 I have made the changes, please look into it.

2021-03-03 07:49 UTC, ayan-biswas0412 requested changes

2021-03-03 07:49 UTC, ayan-biswas0412 commented on hotelontouch/README.md
> +📦src<br>
```suggestion
### File Structure 
📦src<br>
```

2021-03-03 07:49 UTC, ayan-biswas0412 commented on hotelontouch/README.md
> + Regarding Project setup and Contribution, please refer [Wiki](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/wiki)
```suggestion

 Regarding Project setup and Contribution, please refer [Wiki](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/wiki)
```

2021-03-03 08:00 UTC, aniketsingh98571 commented
@ayan-biswas0412 Committed your changes..

2021-03-03 08:37 UTC, ayan-biswas0412 approved these changes
nice work

2021-03-07 21:35 UTC, merged